---
- name: Ensure necessary user config directories exist
  file:
    path: "{{ base_home_dir }}/{{ item }}"
    owner: "{{ base_user.name }}"
    group: "{{ base_user.name }}"
    state: directory
  with_items:
    - '.config'
    - '.config/systemd/user/'

- name: Ensure necessary system config directories exist
  become: True
  file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
  with_items:
    - '/etc/systemd/logind.conf.d/'

- name: Disable suspend on closing the lid
  become: True
  copy:
    src: 10-disable-lid-suspend.conf
    dest: /etc/systemd/logind.conf.d/10-disable-lid-suspend.conf
    owner: root
    group: root
    mode: 0644

- name: Add the user to the sudoers file
  become: True
  lineinfile:
    path: /etc/sudoers
    line: "{{ base_user.name }}\tALL=(ALL) NOPASSWD:ALL"
    state: present
    validate: 'visudo -cf %s'

- name: Install vim configuration
  copy:
    src: vim/
    dest: "{{ base_home_dir }}/.vim"
    owner: "{{ base_user.name }}"
    group: "{{ base_user.name }}"

- name: Create .vimrc symlink
  file:
    src: "{{ base_home_dir }}/.vim/vimrc"
    dest: "{{ base_home_dir }}/.vimrc"
    owner: "{{ base_user.name }}"
    group: "{{ base_user.name }}"
    state: link

- name: Install zsh configuration
  template:
    src: zshrc.j2
    dest: "{{ base_home_dir }}/.zshrc"
    owner: "{{ base_user.name }}"
    group: "{{ base_user.name }}"
