---
- name: Add the user to the sudoers file
  become: True
  lineinfile:
    path: /etc/sudoers
    line: "{{ base_user.name }}\tALL=(ALL) NOPASSWD:ALL"
    state: present

- name: Install vim configuration
  copy:
    src: vim/
    dest: "{{ home_dir }}/.vim"
    owner: "{{ base_user.name }}"
    group: "{{ base_user.name }}"

- name: Create .vimrc symlink
  file:
    src: "{{ home_dir }}/.vim/vimrc"
    dest: "{{ home_dir }}/.vimrc"
    owner: "{{ base_user.name }}"
    group: "{{ base_user.name }}"
    state: link

- name: Install zsh configuration
  template:
    src: zshrc.j2
    dest: "{{ home_dir }}/.zshrc"
    owner: "{{ base_user.name }}"
    group: "{{ base_user.name }}"
