---
- name: Update packages and install base packages
  become: True
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ base_packages + base_extra_packages }}"

- name: "Create the user '{{ base_user_name }}'"
  become: True
  user:
    name: "{{ base_user_name }}"
    createhome: yes
    home: "{{ base_home_dir }}"
    shell: "{{ base_user_shell }}"
    state: present

- name: Create the additional groups if nonexistent
  become: True
  group:
    name: "{{ item }}"
    system: yes
    state: present
  with_items:
    - "{{ base_user_extra_groups }}"

- name: "Add user '{{ base_user_name }}' to necessary groups"
  become: True
  user:
    name: "{{ base_user_name }}"
    groups: "{{ base_user_extra_groups }}"
    append: yes

- name: "Set default editor to '{{ base_editor }}'"
  become: True
  shell: "update-alternatives --set editor {{ base_editor }}"
  register: change_editor
  changed_when: change_editor.stdout != ""

- name: Configure system
  include_tasks: config.yml
  tags:
    - config
