---
- name: Set the hostname of this system
  become: True
  hostname:
    name: "{{ base_hostname }}"

- name: Add base signing keys
  become: True
  apt_key:
    file: "keys/{{ item }}"
    state: present
  with_items: "{{ base_keys + base_extra_keys }}"

- name: Add base repositories
  become: True
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ base_repositories + base_extra_repositories }}"

- name: Update packages and install base packages
  become: True
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ base_packages + base_extra_packages }}"

- name: "Create the user '{{ base_user.name }}'"
  become: True
  user:
    name: "{{ base_user.name }}"
    createhome: yes
    home: "{{ home_dir }}"
    # set the default shell for the user
    shell: "{{ base_user.shell }}"
    state: present

- name: Configure system
  include_tasks: config.yml
  tags:
    - config
